version: '3.7'

services:
  workspace:
    image: golang:1.14.1-buster
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    working_dir: /app
    volumes:
      - .:/app
    tty: true
    command: /bin/bash

  redis:
    image: redis:5.0.8-buster
    tty: true
